[package]
name = "cps"
version = "0.1.0"
edition = "2021"
include = [
    "/Cargo.toml",
    "/LICENSE",
    "/README.md",
    "/src/**",
    "/tests/**",
]

[dependencies]
syn = { version = "1.0", features=["full"] }
proc-macro2 = "1.0.40"
quote = "1.0.20"

[lib]
proc-macro = true
